# Generated by Django 3.0.5 on 2020-04-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200429_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
    ]
